// @generated by scripts/generate-client-schemas.ts - do not edit by hand.
//
// Runtime validation schemas derived from the wire schemas in
// `packages/core/src/api/schema.ts` (the single source of truth): the same
// shapes Elysia validates responses against and `openapi.json` documents.
import { z } from 'zod';

export const apiCrsSchema = z.enum(["wgs84", "gcj02", "bd09", "schematic", "none"]);

export const apiNamesSchema = z.object({ "zh": z.string(), "en": z.string() });

export const apiGeoPointSchema = z.object({ "lon": z.number(), "lat": z.number(), "crs": z.enum(["wgs84", "gcj02", "bd09", "schematic", "none"]) });

export const apiSchematicPointSchema = z.object({ "x": z.number(), "y": z.number(), "crs": z.enum(["wgs84", "gcj02", "bd09", "schematic", "none"]) });

export const apiLineModeSchema = z.enum(["metro", "suburban_rail", "light_rail", "tram", "monorail", "airport_express", "other"]);

export const apiLineStatusSchema = z.enum(["operating", "partially_operating", "under_construction", "planned", "closed"]);

export const apiLineSchema = z.object({ "id": z.string(), "name": z.string(), "names": apiNamesSchema, "color": z.string().optional(), "text_color": z.string().optional(), "short_name": z.string(), "mode": z.enum(["metro", "suburban_rail", "light_rail", "tram", "monorail", "airport_express", "other"]), "status": z.enum(["operating", "partially_operating", "under_construction", "planned", "closed"]), "loop": z.boolean() });

export const apiLineListSchema = z.array(apiLineSchema);

export const apiStationStatusSchema = z.enum(["operating", "out_of_service", "closed", "under_construction", "planned"]);

export const apiStationSchema = z.object({ "id": z.string(), "name": z.string(), "names": apiNamesSchema, "location": apiGeoPointSchema.optional(), "schematic": apiSchematicPointSchema.optional(), "status": z.enum(["operating", "out_of_service", "closed", "under_construction", "planned"]), "lines": z.array(z.string()), "is_interchange": z.boolean() });

export const apiStationListSchema = z.array(apiStationSchema);

export const apiDirectionTypeSchema = z.enum(["linear", "loop_inner", "loop_outer"]);

export const apiTimetableStatusSchema = z.object({ "timetable_id": z.string(), "station_id": z.string(), "line_id": z.string(), "destination_stop_id": z.string().optional(), "is_in_service": z.boolean(), "first_train": z.string(), "last_train": z.string(), "timezone": z.string(), "now": z.string() });

export const apiStopSchema = z.object({ "id": z.string(), "station_id": z.string(), "line_id": z.string(), "sequence": z.number(), "is_terminal": z.boolean().optional(), "location": apiGeoPointSchema.optional(), "schematic": apiSchematicPointSchema.optional() });

export const apiStopListSchema = z.array(apiStopSchema);

export const apiPatternSchema = z.object({ "id": z.string(), "line_id": z.string(), "name": z.string().optional(), "names": apiNamesSchema.optional(), "stop_ids": z.array(z.string()), "origin_stop_id": z.string(), "terminal_stop_id": z.string(), "is_primary": z.boolean(), "junction_stop_id": z.string().optional(), "color": z.string().optional() });

export const apiPatternListSchema = z.array(apiPatternSchema);

export const apiSegmentDirectionSchema = z.enum(["both", "forward", "backward"]);

export const apiTravelTimeSourceSchema = z.enum(["source", "last_train", "estimated"]);

export const apiSegmentSchema = z.object({ "id": z.string(), "line_id": z.string(), "from_stop_id": z.string(), "to_stop_id": z.string(), "from_station_id": z.string(), "to_station_id": z.string(), "direction": z.enum(["both", "forward", "backward"]), "travel_time_seconds": z.number().optional(), "travel_time_source": apiTravelTimeSourceSchema.optional(), "distance_km": z.number().optional() });

export const apiSegmentListSchema = z.array(apiSegmentSchema);

export const apiTransferSchema = z.object({ "id": z.string(), "station_id": z.string(), "from_line_id": z.string(), "to_line_id": z.string(), "from_stop_id": z.string().optional(), "to_stop_id": z.string().optional(), "walk_time_seconds": z.number().optional(), "walk_distance_meters": z.number().optional(), "is_out_of_station": z.boolean().optional() });

export const apiTransferListSchema = z.array(apiTransferSchema);

export const apiTimetableSchema = z.object({ "id": z.string(), "station_id": z.string(), "stop_id": z.string(), "line_id": z.string(), "destination_stop_id": z.string().optional(), "origin_stop_id": z.string().optional(), "pattern_id": z.string(), "direction_type": apiDirectionTypeSchema.optional(), "direction_label": z.string().optional(), "first_train": z.array(z.string()), "last_train": z.array(z.string()), "is_arrival": z.boolean().optional(), "service": z.string().optional() });

export const apiTimetableListSchema = z.array(apiTimetableSchema);

export const apiStationDetailSchema = z.object({ "id": z.string(), "name": z.string(), "names": apiNamesSchema, "location": apiGeoPointSchema.optional(), "schematic": apiSchematicPointSchema.optional(), "status": z.array(apiTimetableStatusSchema), "lines": z.array(z.string()), "is_interchange": z.boolean(), "transfers": z.array(apiTransferSchema), "timetables": z.array(apiTimetableSchema) });

export const apiFareMatrixSchema = z.object({ "currency": z.string(), "unit": z.string(), "station_ids": z.array(z.string()), "fares": z.array(z.array(z.union([z.number(), z.null()]))) });

export const apiFareRowSchema = z.object({ "from_station_id": z.string(), "currency": z.string(), "unit": z.string(), "fares": z.record(z.string(), z.union([z.number(), z.null()])) });

export const apiCitySchema = z.object({ "id": z.string(), "name": apiNamesSchema, "country": z.string(), "population": z.union([z.number(), z.null()]), "area": z.union([z.number(), z.null()]), "location": z.union([z.object({ "type": z.literal("Point"), "coordinates": z.tuple([z.number(), z.number()]) }), z.null()]) });

export const apiRoutingDefaultsSchema = z.object({ "weight": z.enum(["time", "distance"]), "default_transfer_seconds": z.number(), "max_transfer_seconds": z.number().optional() });

export const apiNetworkSchema = z.object({ "id": z.string(), "name": z.string(), "names": apiNamesSchema, "city": apiCitySchema, "country_code": z.string(), "currency": z.string(), "timezone": z.string(), "coordinate_system": z.enum(["wgs84", "gcj02", "bd09", "schematic", "none"]), "default_units": z.object({ "distance": z.string(), "time": z.string(), "speed": z.string() }), "routing": apiRoutingDefaultsSchema, "synced_at": z.string().optional() });

export const apiNetworkListSchema = z.object({ "networks": z.array(apiNetworkSchema) });

export const apiStopNodeSchema = z.object({ "id": z.string(), "station_id": z.string(), "line_id": z.string() });

export const apiStopEdgeSchema = z.object({ "from": z.string(), "to": z.string(), "kind": z.enum(["ride", "transfer"]), "line_id": z.string().optional(), "seconds": z.number().optional(), "distance_km": z.number().optional(), "weight": z.number().optional() });

export const apiStopGraphSchema = z.object({ "network_id": z.string(), "weight": z.enum(["seconds", "km"]), "routing": apiRoutingDefaultsSchema, "nodes": z.array(apiStopNodeSchema), "edges": z.array(apiStopEdgeSchema) });

export const apiRideLegSchema = z.object({ "kind": z.literal("ride"), "line_id": z.string().optional(), "from_stop_id": z.string(), "to_stop_id": z.string(), "from_station_id": z.string(), "to_station_id": z.string(), "seconds": z.number(), "station_ids": z.array(z.string()).optional(), "pattern_id": z.string().optional(), "headsign_station_id": z.string().optional(), "headsign_names": apiNamesSchema.optional() });

export const apiTransferLegSchema = z.object({ "kind": z.literal("transfer"), "line_id": z.string().optional(), "from_stop_id": z.string(), "to_stop_id": z.string(), "from_station_id": z.string(), "to_station_id": z.string(), "seconds": z.number(), "same_line_direction_change": z.boolean().optional() });

export const apiRouteLegSchema = z.discriminatedUnion("kind", [apiRideLegSchema, apiTransferLegSchema]);

export const apiRoutePlanSchema = z.object({ "from_station_id": z.string(), "to_station_id": z.string(), "total_seconds": z.number(), "transfers": z.number(), "legs": z.array(apiRouteLegSchema), "fare": z.union([z.number(), z.null()]), "currency": z.union([z.string(), z.null()]) });

export const apiTravelTimeEntrySchema = z.object({ "station_id": z.string(), "seconds": z.number() });

export const apiTravelTimesSchema = z.object({ "from_station_id": z.string(), "weight": z.enum(["seconds", "km"]), "within": z.union([z.number(), z.null()]), "stations": z.array(apiTravelTimeEntrySchema) });

export const apiNearestStationSchema = z.object({ "station_id": z.string(), "distance_km": z.number() });

export const apiNearestStationsSchema = z.object({ "network_id": z.string(), "query": z.object({ "lon": z.number(), "lat": z.number() }), "stations": z.array(apiNearestStationSchema) });

export const apiHealthSchema = z.object({ "status": z.literal("ok") });

export const apiErrorSchema = z.object({ "error": z.string() });

/** Every generated schema, keyed by its wire name. */
export const apiSchemas = {
  ApiCrs: apiCrsSchema,
  ApiNames: apiNamesSchema,
  ApiGeoPoint: apiGeoPointSchema,
  ApiSchematicPoint: apiSchematicPointSchema,
  ApiLineMode: apiLineModeSchema,
  ApiLineStatus: apiLineStatusSchema,
  ApiLine: apiLineSchema,
  ApiLineList: apiLineListSchema,
  ApiStationStatus: apiStationStatusSchema,
  ApiStation: apiStationSchema,
  ApiStationList: apiStationListSchema,
  ApiDirectionType: apiDirectionTypeSchema,
  ApiTimetableStatus: apiTimetableStatusSchema,
  ApiStop: apiStopSchema,
  ApiStopList: apiStopListSchema,
  ApiPattern: apiPatternSchema,
  ApiPatternList: apiPatternListSchema,
  ApiSegmentDirection: apiSegmentDirectionSchema,
  ApiTravelTimeSource: apiTravelTimeSourceSchema,
  ApiSegment: apiSegmentSchema,
  ApiSegmentList: apiSegmentListSchema,
  ApiTransfer: apiTransferSchema,
  ApiTransferList: apiTransferListSchema,
  ApiTimetable: apiTimetableSchema,
  ApiTimetableList: apiTimetableListSchema,
  ApiStationDetail: apiStationDetailSchema,
  ApiFareMatrix: apiFareMatrixSchema,
  ApiFareRow: apiFareRowSchema,
  ApiCity: apiCitySchema,
  ApiRoutingDefaults: apiRoutingDefaultsSchema,
  ApiNetwork: apiNetworkSchema,
  ApiNetworkList: apiNetworkListSchema,
  ApiStopNode: apiStopNodeSchema,
  ApiStopEdge: apiStopEdgeSchema,
  ApiStopGraph: apiStopGraphSchema,
  ApiRideLeg: apiRideLegSchema,
  ApiTransferLeg: apiTransferLegSchema,
  ApiRouteLeg: apiRouteLegSchema,
  ApiRoutePlan: apiRoutePlanSchema,
  ApiTravelTimeEntry: apiTravelTimeEntrySchema,
  ApiTravelTimes: apiTravelTimesSchema,
  ApiNearestStation: apiNearestStationSchema,
  ApiNearestStations: apiNearestStationsSchema,
  ApiHealth: apiHealthSchema,
  ApiError: apiErrorSchema
};
