// AUTO-GENERATED by scripts/build-worker-data.ts — do not edit.
// Canonical JSON bundled for the Vercel API function (no filesystem at runtime).
import cnBeijingnetwork from "../../../data/cn-beijing/network.json" with { type: "json" };
import cnBeijinglines from "../../../data/cn-beijing/lines.json" with { type: "json" };
import cnBeijingstations from "../../../data/cn-beijing/stations.json" with { type: "json" };
import cnBeijingstops from "../../../data/cn-beijing/stops.json" with { type: "json" };
import cnBeijingpatterns from "../../../data/cn-beijing/patterns.json" with { type: "json" };
import cnBeijingsegments from "../../../data/cn-beijing/segments.json" with { type: "json" };
import cnBeijingtransfers from "../../../data/cn-beijing/transfers.json" with { type: "json" };
import cnBeijingtimetables from "../../../data/cn-beijing/timetables.json" with { type: "json" };
import cnBeijingfares from "../../../data/cn-beijing/fares.json" with { type: "json" };
import cnGuangzhounetwork from "../../../data/cn-guangzhou/network.json" with { type: "json" };
import cnGuangzhoulines from "../../../data/cn-guangzhou/lines.json" with { type: "json" };
import cnGuangzhoustations from "../../../data/cn-guangzhou/stations.json" with { type: "json" };
import cnGuangzhoustops from "../../../data/cn-guangzhou/stops.json" with { type: "json" };
import cnGuangzhoupatterns from "../../../data/cn-guangzhou/patterns.json" with { type: "json" };
import cnGuangzhousegments from "../../../data/cn-guangzhou/segments.json" with { type: "json" };
import cnGuangzhoutransfers from "../../../data/cn-guangzhou/transfers.json" with { type: "json" };
import cnGuangzhoutimetables from "../../../data/cn-guangzhou/timetables.json" with { type: "json" };
import cnGuangzhoufares from "../../../data/cn-guangzhou/fares.json" with { type: "json" };
import cnHangzhounetwork from "../../../data/cn-hangzhou/network.json" with { type: "json" };
import cnHangzhoulines from "../../../data/cn-hangzhou/lines.json" with { type: "json" };
import cnHangzhoustations from "../../../data/cn-hangzhou/stations.json" with { type: "json" };
import cnHangzhoustops from "../../../data/cn-hangzhou/stops.json" with { type: "json" };
import cnHangzhoupatterns from "../../../data/cn-hangzhou/patterns.json" with { type: "json" };
import cnHangzhousegments from "../../../data/cn-hangzhou/segments.json" with { type: "json" };
import cnHangzhoutransfers from "../../../data/cn-hangzhou/transfers.json" with { type: "json" };
import cnHangzhoutimetables from "../../../data/cn-hangzhou/timetables.json" with { type: "json" };
import cnHangzhoufares from "../../../data/cn-hangzhou/fares.json" with { type: "json" };
import cnShanghainetwork from "../../../data/cn-shanghai/network.json" with { type: "json" };
import cnShanghailines from "../../../data/cn-shanghai/lines.json" with { type: "json" };
import cnShanghaistations from "../../../data/cn-shanghai/stations.json" with { type: "json" };
import cnShanghaistops from "../../../data/cn-shanghai/stops.json" with { type: "json" };
import cnShanghaipatterns from "../../../data/cn-shanghai/patterns.json" with { type: "json" };
import cnShanghaisegments from "../../../data/cn-shanghai/segments.json" with { type: "json" };
import cnShanghaitransfers from "../../../data/cn-shanghai/transfers.json" with { type: "json" };
import cnShanghaitimetables from "../../../data/cn-shanghai/timetables.json" with { type: "json" };
import cnShanghaifares from "../../../data/cn-shanghai/fares.json" with { type: "json" };
import cnShenzhennetwork from "../../../data/cn-shenzhen/network.json" with { type: "json" };
import cnShenzhenlines from "../../../data/cn-shenzhen/lines.json" with { type: "json" };
import cnShenzhenstations from "../../../data/cn-shenzhen/stations.json" with { type: "json" };
import cnShenzhenstops from "../../../data/cn-shenzhen/stops.json" with { type: "json" };
import cnShenzhenpatterns from "../../../data/cn-shenzhen/patterns.json" with { type: "json" };
import cnShenzhensegments from "../../../data/cn-shenzhen/segments.json" with { type: "json" };
import cnShenzhentransfers from "../../../data/cn-shenzhen/transfers.json" with { type: "json" };
import cnShenzhentimetables from "../../../data/cn-shenzhen/timetables.json" with { type: "json" };
import cnShenzhenfares from "../../../data/cn-shenzhen/fares.json" with { type: "json" };
import cnSuzhounetwork from "../../../data/cn-suzhou/network.json" with { type: "json" };
import cnSuzhoulines from "../../../data/cn-suzhou/lines.json" with { type: "json" };
import cnSuzhoustations from "../../../data/cn-suzhou/stations.json" with { type: "json" };
import cnSuzhoustops from "../../../data/cn-suzhou/stops.json" with { type: "json" };
import cnSuzhoupatterns from "../../../data/cn-suzhou/patterns.json" with { type: "json" };
import cnSuzhousegments from "../../../data/cn-suzhou/segments.json" with { type: "json" };
import cnSuzhoutransfers from "../../../data/cn-suzhou/transfers.json" with { type: "json" };
import cnSuzhoutimetables from "../../../data/cn-suzhou/timetables.json" with { type: "json" };
import cnSuzhoufares from "../../../data/cn-suzhou/fares.json" with { type: "json" };

import type { RawNetworkFiles } from "../../core/src/data/types.js";

export const files: Record<string, RawNetworkFiles> = {
  "cn-beijing": {
    network: cnBeijingnetwork,
    lines: cnBeijinglines,
    stations: cnBeijingstations,
    stops: cnBeijingstops,
    patterns: cnBeijingpatterns,
    segments: cnBeijingsegments,
    transfers: cnBeijingtransfers,
    timetables: cnBeijingtimetables,
    fares: cnBeijingfares,
  },
  "cn-guangzhou": {
    network: cnGuangzhounetwork,
    lines: cnGuangzhoulines,
    stations: cnGuangzhoustations,
    stops: cnGuangzhoustops,
    patterns: cnGuangzhoupatterns,
    segments: cnGuangzhousegments,
    transfers: cnGuangzhoutransfers,
    timetables: cnGuangzhoutimetables,
    fares: cnGuangzhoufares,
  },
  "cn-hangzhou": {
    network: cnHangzhounetwork,
    lines: cnHangzhoulines,
    stations: cnHangzhoustations,
    stops: cnHangzhoustops,
    patterns: cnHangzhoupatterns,
    segments: cnHangzhousegments,
    transfers: cnHangzhoutransfers,
    timetables: cnHangzhoutimetables,
    fares: cnHangzhoufares,
  },
  "cn-shanghai": {
    network: cnShanghainetwork,
    lines: cnShanghailines,
    stations: cnShanghaistations,
    stops: cnShanghaistops,
    patterns: cnShanghaipatterns,
    segments: cnShanghaisegments,
    transfers: cnShanghaitransfers,
    timetables: cnShanghaitimetables,
    fares: cnShanghaifares,
  },
  "cn-shenzhen": {
    network: cnShenzhennetwork,
    lines: cnShenzhenlines,
    stations: cnShenzhenstations,
    stops: cnShenzhenstops,
    patterns: cnShenzhenpatterns,
    segments: cnShenzhensegments,
    transfers: cnShenzhentransfers,
    timetables: cnShenzhentimetables,
    fares: cnShenzhenfares,
  },
  "cn-suzhou": {
    network: cnSuzhounetwork,
    lines: cnSuzhoulines,
    stations: cnSuzhoustations,
    stops: cnSuzhoustops,
    patterns: cnSuzhoupatterns,
    segments: cnSuzhousegments,
    transfers: cnSuzhoutransfers,
    timetables: cnSuzhoutimetables,
    fares: cnSuzhoufares,
  },
};
