// AUTO-GENERATED by scripts/build-worker-data.ts — do not edit.
// Canonical JSON bundled for the Cloudflare Worker (no filesystem at the edge).
import cnBeijingnetwork from "../../../data/cn-beijing/network.json";
import cnBeijinglines from "../../../data/cn-beijing/lines.json";
import cnBeijingstations from "../../../data/cn-beijing/stations.json";
import cnBeijingstops from "../../../data/cn-beijing/stops.json";
import cnBeijingpatterns from "../../../data/cn-beijing/patterns.json";
import cnBeijingsegments from "../../../data/cn-beijing/segments.json";
import cnBeijingtransfers from "../../../data/cn-beijing/transfers.json";
import cnBeijingtimetables from "../../../data/cn-beijing/timetables.json";
import cnBeijingfares from "../../../data/cn-beijing/fares.json";
import cnGuangzhounetwork from "../../../data/cn-guangzhou/network.json";
import cnGuangzhoulines from "../../../data/cn-guangzhou/lines.json";
import cnGuangzhoustations from "../../../data/cn-guangzhou/stations.json";
import cnGuangzhoustops from "../../../data/cn-guangzhou/stops.json";
import cnGuangzhoupatterns from "../../../data/cn-guangzhou/patterns.json";
import cnGuangzhousegments from "../../../data/cn-guangzhou/segments.json";
import cnGuangzhoutransfers from "../../../data/cn-guangzhou/transfers.json";
import cnGuangzhoutimetables from "../../../data/cn-guangzhou/timetables.json";
import cnGuangzhoufares from "../../../data/cn-guangzhou/fares.json";
import cnShanghainetwork from "../../../data/cn-shanghai/network.json";
import cnShanghailines from "../../../data/cn-shanghai/lines.json";
import cnShanghaistations from "../../../data/cn-shanghai/stations.json";
import cnShanghaistops from "../../../data/cn-shanghai/stops.json";
import cnShanghaipatterns from "../../../data/cn-shanghai/patterns.json";
import cnShanghaisegments from "../../../data/cn-shanghai/segments.json";
import cnShanghaitransfers from "../../../data/cn-shanghai/transfers.json";
import cnShanghaitimetables from "../../../data/cn-shanghai/timetables.json";
import cnShanghaifares from "../../../data/cn-shanghai/fares.json";
import cnShenzhennetwork from "../../../data/cn-shenzhen/network.json";
import cnShenzhenlines from "../../../data/cn-shenzhen/lines.json";
import cnShenzhenstations from "../../../data/cn-shenzhen/stations.json";
import cnShenzhenstops from "../../../data/cn-shenzhen/stops.json";
import cnShenzhenpatterns from "../../../data/cn-shenzhen/patterns.json";
import cnShenzhensegments from "../../../data/cn-shenzhen/segments.json";
import cnShenzhentransfers from "../../../data/cn-shenzhen/transfers.json";
import cnShenzhentimetables from "../../../data/cn-shenzhen/timetables.json";
import cnShenzhenfares from "../../../data/cn-shenzhen/fares.json";
import cnSuzhounetwork from "../../../data/cn-suzhou/network.json";
import cnSuzhoulines from "../../../data/cn-suzhou/lines.json";
import cnSuzhoustations from "../../../data/cn-suzhou/stations.json";
import cnSuzhoustops from "../../../data/cn-suzhou/stops.json";
import cnSuzhoupatterns from "../../../data/cn-suzhou/patterns.json";
import cnSuzhousegments from "../../../data/cn-suzhou/segments.json";
import cnSuzhoutransfers from "../../../data/cn-suzhou/transfers.json";
import cnSuzhoutimetables from "../../../data/cn-suzhou/timetables.json";
import cnSuzhoufares from "../../../data/cn-suzhou/fares.json";

import type { RawNetworkFiles } from "../../core/src/data/types.js";

export const files: Record<string, RawNetworkFiles> = {
  "cn-beijing": {
    network: cnBeijingnetwork,
    lines: cnBeijinglines,
    stations: cnBeijingstations,
    stops: cnBeijingstops,
    patterns: cnBeijingpatterns,
    segments: cnBeijingsegments,
    transfers: cnBeijingtransfers,
    timetables: cnBeijingtimetables,
    fares: cnBeijingfares,
  },
  "cn-guangzhou": {
    network: cnGuangzhounetwork,
    lines: cnGuangzhoulines,
    stations: cnGuangzhoustations,
    stops: cnGuangzhoustops,
    patterns: cnGuangzhoupatterns,
    segments: cnGuangzhousegments,
    transfers: cnGuangzhoutransfers,
    timetables: cnGuangzhoutimetables,
    fares: cnGuangzhoufares,
  },
  "cn-shanghai": {
    network: cnShanghainetwork,
    lines: cnShanghailines,
    stations: cnShanghaistations,
    stops: cnShanghaistops,
    patterns: cnShanghaipatterns,
    segments: cnShanghaisegments,
    transfers: cnShanghaitransfers,
    timetables: cnShanghaitimetables,
    fares: cnShanghaifares,
  },
  "cn-shenzhen": {
    network: cnShenzhennetwork,
    lines: cnShenzhenlines,
    stations: cnShenzhenstations,
    stops: cnShenzhenstops,
    patterns: cnShenzhenpatterns,
    segments: cnShenzhensegments,
    transfers: cnShenzhentransfers,
    timetables: cnShenzhentimetables,
    fares: cnShenzhenfares,
  },
  "cn-suzhou": {
    network: cnSuzhounetwork,
    lines: cnSuzhoulines,
    stations: cnSuzhoustations,
    stops: cnSuzhoustops,
    patterns: cnSuzhoupatterns,
    segments: cnSuzhousegments,
    transfers: cnSuzhoutransfers,
    timetables: cnSuzhoutimetables,
    fares: cnSuzhoufares,
  },
};
