// AUTO-GENERATED by scripts/build-worker-data.ts — do not edit.
// Canonical JSON bundled for the Cloudflare Worker (no filesystem at the edge).
import cnBjnetwork from "../../../data/cn-bj/network.json";
import cnBjlines from "../../../data/cn-bj/lines.json";
import cnBjstations from "../../../data/cn-bj/stations.json";
import cnBjstops from "../../../data/cn-bj/stops.json";
import cnBjpatterns from "../../../data/cn-bj/patterns.json";
import cnBjsegments from "../../../data/cn-bj/segments.json";
import cnBjtransfers from "../../../data/cn-bj/transfers.json";
import cnBjtimetables from "../../../data/cn-bj/timetables.json";
import cnBjfares from "../../../data/cn-bj/fares.json";
import cnGznetwork from "../../../data/cn-gz/network.json";
import cnGzlines from "../../../data/cn-gz/lines.json";
import cnGzstations from "../../../data/cn-gz/stations.json";
import cnGzstops from "../../../data/cn-gz/stops.json";
import cnGzpatterns from "../../../data/cn-gz/patterns.json";
import cnGzsegments from "../../../data/cn-gz/segments.json";
import cnGztransfers from "../../../data/cn-gz/transfers.json";
import cnGztimetables from "../../../data/cn-gz/timetables.json";
import cnGzfares from "../../../data/cn-gz/fares.json";
import cnShnetwork from "../../../data/cn-sh/network.json";
import cnShlines from "../../../data/cn-sh/lines.json";
import cnShstations from "../../../data/cn-sh/stations.json";
import cnShstops from "../../../data/cn-sh/stops.json";
import cnShpatterns from "../../../data/cn-sh/patterns.json";
import cnShsegments from "../../../data/cn-sh/segments.json";
import cnShtransfers from "../../../data/cn-sh/transfers.json";
import cnShtimetables from "../../../data/cn-sh/timetables.json";
import cnShfares from "../../../data/cn-sh/fares.json";

import type { RawNetworkFiles } from "../../core/src/data/types.js";

export const files: Record<string, RawNetworkFiles> = {
  "cn-bj": {
    network: cnBjnetwork,
    lines: cnBjlines,
    stations: cnBjstations,
    stops: cnBjstops,
    patterns: cnBjpatterns,
    segments: cnBjsegments,
    transfers: cnBjtransfers,
    timetables: cnBjtimetables,
    fares: cnBjfares,
  },
  "cn-gz": {
    network: cnGznetwork,
    lines: cnGzlines,
    stations: cnGzstations,
    stops: cnGzstops,
    patterns: cnGzpatterns,
    segments: cnGzsegments,
    transfers: cnGztransfers,
    timetables: cnGztimetables,
    fares: cnGzfares,
  },
  "cn-sh": {
    network: cnShnetwork,
    lines: cnShlines,
    stations: cnShstations,
    stops: cnShstops,
    patterns: cnShpatterns,
    segments: cnShsegments,
    transfers: cnShtransfers,
    timetables: cnShtimetables,
    fares: cnShfares,
  },
};
