/**
 * Generate `packages/api-worker/src/data.generated.ts`, which statically imports
 * every canonical JSON file so the Vercel API function can bundle them (no
 * filesystem required at runtime).
 *
 * Usage: `bun run scripts/build-worker-data.ts`
 */
import { mkdir, readdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DATA_ROOT = resolve(process.env.OPENMETRO_DATA_ROOT ?? join(REPO_ROOT, 'data'));
const OUT = join(REPO_ROOT, 'packages/api-worker/src/data.generated.ts');

const CANONICAL_FILES = [
  'network.json',
  'lines.json',
  'stations.json',
  'stops.json',
  'patterns.json',
  'segments.json',
  'transfers.json',
  'timetables.json',
  'fares.json'
];

const KEY_BY_FILE: Record<string, string> = {
  'network.json': 'network',
  'lines.json': 'lines',
  'stations.json': 'stations',
  'stops.json': 'stops',
  'patterns.json': 'patterns',
  'segments.json': 'segments',
  'transfers.json': 'transfers',
  'timetables.json': 'timetables',
  'fares.json': 'fares'
};

const camel = (s: string) => s.replace(/[^a-zA-Z0-9]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ''));

async function main(): Promise<void> {
  const ids = (await readdir(DATA_ROOT, { withFileTypes: true }))
    .filter((e) => e.isDirectory() && !e.name.startsWith('.'))
    .map((e) => e.name)
    .sort();

  const imports: string[] = [];
  const entries: string[] = [];

  for (const id of ids) {
    const varPrefix = camel(id);
    const fields: string[] = [];
    for (const file of CANONICAL_FILES) {
      const raw = await Bun.file(join(DATA_ROOT, id, file)).exists();
      if (!raw) continue;
      const varName = `${varPrefix}${camel(file.replace('.json', ''))}`;
      // Node/Vercel require import attributes for JSON modules (NodeNext).
      imports.push(`import ${varName} from "../../../data/${id}/${file}" with { type: "json" };`);
      fields.push(`    ${KEY_BY_FILE[file]}: ${varName},`);
    }
    entries.push(`  "${id}": {\n${fields.join('\n')}\n  },`);
  }

  const content = [
    '// AUTO-GENERATED by scripts/build-worker-data.ts — do not edit.',
    '// Canonical JSON bundled for the Vercel API function (no filesystem at runtime).',
    ...imports,
    '',
    'import type { RawNetworkFiles } from "../../core/src/data/types.js";',
    '',
    'export const files: Record<string, RawNetworkFiles> = {',
    entries.join('\n'),
    '};',
    ''
  ].join('\n');

  await mkdir(dirname(OUT), { recursive: true });
  await writeFile(OUT, content, 'utf-8');
  console.log(`generated ${OUT} (${ids.length} networks)`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
